namespace Reportr.Data.Dapper
{
    using global::Dapper;
    using Reportr.Data.Querying;
    using Reportr.Filtering;
    using System.Collections.Generic;
    using System.Data;
    using System.Threading.Tasks;

    /// <summary>
    /// Represents a base class for generic Dapper report queries
    /// </summary>
    /// <typeparam name="T">The query output type</typeparam>
    public abstract class DapperQuery<T> : QueryBase
    {
        private QueryColumnInfo[] _columns = null;

        /// <summary>
        /// Constructs the query with a Dapper data source
        /// </summary>
        /// <param name="dataSource">The data source</param>
        public DapperQuery
            (
                DapperDataSource dataSource
            )

            : base(dataSource)
        {
            _columns = ResolveColumns<T>();
        }
        
        /// <summary>
        /// Gets an array of the columns generated by the query
        /// </summary>
        public override QueryColumnInfo[] Columns
        {
            get
            {
                if (_columns == null || _columns.Length == 0)
                {
                    _columns = ResolveColumns<T>();
                }

                return _columns;
            }
        }

        /// <summary>
        /// Gets the database connection from the data source
        /// </summary>
        /// <returns>The database connection</returns>
        protected IDbConnection GetConnection()
        {
            return ((DapperDataSource)this.DataSource).Connection;
        }

        /// <summary>
        /// Compiles the SQL statement to be executed by the query
        /// </summary>
        /// <param name="parameterValues">The parameter values</param>
        /// <returns>The SQL query generated</returns>
        protected abstract string CompileSql
        (
            params ParameterValue[] parameterValues
        );

        /// <summary>
        /// Asynchronously fetches the query data using the parameter values
        /// </summary>
        /// <param name="parameterValues">The parameter values</param>
        /// <returns>The query data in the form of an array of rows</returns>
        protected override async Task<IEnumerable<QueryRow>> FetchDataAsync
            (
                params ParameterValue[] parameterValues
            )
        {
            Validate.IsNotNull(parameterValues);

            var connection = GetConnection();
            var sql = CompileSql(parameterValues);

            var queryResults = await connection.QueryAsync<T>
            (
                sql
            )
            .ConfigureAwait
            (
                false
            );
            
            var rows = ConvertToRows<T>
            (
                queryResults
            );

            return rows;
        }
    }
}
