namespace Reportr.Components.Metrics
{
    /// <summary>
    /// Defines a contract for a single statistic
    /// </summary>
    public interface IStatistic : IReportComponentOutput
    {
        /// <summary>
        /// Gets the statistic definition
        /// </summary>
        StatisticDefinition Definition { get; }

        /// <summary>
        /// Gets the value generated by the statistic
        /// </summary>
        double Value { get; }

        /// <summary>
        /// Gets the lower range value
        /// </summary>
        double? LowerRange { get; }

        /// <summary>
        /// Gets the upper range value
        /// </summary>
        double? UpperRange { get; }

        /// <summary>
        /// Gets a flag indicating if the value has a range that it fits into
        /// </summary>
        bool HasRange { get; }
    }
}
