namespace Reportr.Components.Metrics
{
    using Reportr.Data.Querying;
    using System;
    
    /// <summary>
    /// Represents a single report statistic
    /// </summary>
    public class Statistic : ReportComponentOutputBase
    {
        /// <summary>
        /// Constructs the statistic with the details
        /// </summary>
        /// <param name="definition">The statistic definition</param>
        /// <param name="results">The query results</param>
        /// <param name="value">The value calculated</param>
        public Statistic
            (
                StatisticDefinition definition,
                QueryResults results,
                double value
            )
            : base(definition, results)
        {
            Validate.IsNotNull(definition);
            Validate.IsNotNull(results);

            this.Value = value;
            this.HasRange = false;
        }
        
        /// <summary>
        /// Gets the value generated by the statistic
        /// </summary>
        public double Value { get; private set; }

        /// <summary>
        /// Gets the lower range value
        /// </summary>
        public double? LowerRange { get; private set; }

        /// <summary>
        /// Gets the upper range value
        /// </summary>
        public double? UpperRange { get; private set; }

        /// <summary>
        /// Gets a flag indicating if the value has a range that it fits into
        /// </summary>
        public bool HasRange { get; private set; }

        /// <summary>
        /// Adds the range values to the statistic result
        /// </summary>
        /// <param name="lower">The lower range</param>
        /// <param name="upper">The upper range</param>
        /// <returns>The updated statistic result</returns>
        public Statistic WithRange
            (
                double? lower,
                double? upper
            )
        {
            if (lower == null && upper == null)
            {
                throw new InvalidOperationException
                (
                    "A lower or upper range value must be specified."
                );
            }

            this.LowerRange = lower;
            this.UpperRange = upper;
            this.HasRange = true;

            return this;
        }

        /// <summary>
        /// Gets the statistic action
        /// </summary>
        public ReportActionOutput Action { get; private set; }

        /// <summary>
        /// Adds the action to the statistic
        /// </summary>
        /// <param name="action">The statistic action</param>
        /// <returns>The updated statistic</returns>
        public Statistic WithAction
            (
                ReportActionOutput action
            )
        {
            Validate.IsNotNull(action);

            this.Action = action;

            return this;
        }
    }
}
