namespace Reportr.Querying
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents the result of the execution of a query
    /// </summary>
    public class QueryResult : ReportComponentOutput, IEnumerable<QueryRow>
    {
        /// <summary>
        /// Constructs the query result with the details
        /// </summary>
        /// <param name="query">The query that generated the result</param>
        /// <param name="executionTime">The execution time in milliseconds</param>
        /// <param name="success">True, if the query executed successfully</param>
        public QueryResult
            (
                IQuery query,
                int executionTime,
                bool success = true
            )
            : base
            (
                query,
                executionTime,
                success
            )
        {
            Validate.IsNotNull(query);

            this.Columns = new QueryColumnInfo[] { };
            this.Rows = new QueryRow[] { };
        }

        /// <summary>
        /// Gets an array of the columns from the query
        /// </summary>
        public QueryColumnInfo[] Columns { get; private set; }

        /// <summary>
        /// Gets an array of the rows in the result
        /// </summary>
        public QueryRow[] Rows { get; private set; }

        /// <summary>
        /// Adds the query data to the result
        /// </summary>
        /// <param name="columns">The queries columns</param>
        /// <param name="rows">Th rows generated by the query</param>
        /// <returns>The updated query result</returns>
        public QueryResult WithData
            (
                IEnumerable<QueryColumnInfo> columns,
                params QueryRow[] rows
            )
        {
            Validate.IsNotNull(columns);
            Validate.IsNotNull(rows);

            if (false == columns.Any())
            {
                throw new ArgumentException
                (
                    "At least one column is required to populate the query."
                );
            }

            foreach (var set in columns.ToList())
            {
                var name = set.Name;

                var matchCount = columns.Count
                (
                    s => s.Name.Trim().ToLower() == name.Trim().ToLower()
                );

                if (matchCount > 1)
                {
                    var message = "The column name '{0}' can only be used once.";

                    throw new ArgumentException
                    (
                        String.Format(message, name)
                    );
                }
            }

            ValidateRows
            (
                columns.ToArray(),
                rows
            );

            this.Columns = columns.ToArray();
            this.Rows = rows;

            return this;
        }

        /// <summary>
        /// Validates a collection of rows against columns
        /// </summary>
        /// <param name="columns">The columns</param>
        /// <param name="rows">The rows to validate</param>
        private void ValidateRows
            (
                QueryColumnInfo[] columns,
                QueryRow[] rows
            )
        {
            var columnCount = columns.Length;

            foreach (var row in rows)
            {
                var cellCount = row.Cells.Length;

                if (cellCount != columnCount)
                {
                    var message = "{0} cells were expected, but {1} were found.";

                    throw new InvalidOperationException
                    (
                        String.Format
                        (
                            message,
                            columnCount,
                            cellCount
                        )
                    );
                }

                // Ensure the column names match those in the cells
                foreach (var column in columns)
                {
                    var matchFound = row.Cells.Any
                    (
                        c => c.ColumnName == column.Name
                    );

                    if (false == matchFound)
                    {
                        var message = "No data was found for the column '{0}'.";

                        throw new InvalidOperationException
                        (
                            String.Format
                            (
                                message,
                                column.Name
                            )
                        );
                    }
                }
            }
        }

        /// <summary>
        /// Gets the row at the index specified
        /// </summary>
        /// <param name="index">The row index (zero based)</param>
        /// <returns>The matching query row</returns>
        public QueryRow this[int index]
        {
            get
            {
                return this.Rows[index];
            }
        }

        /// <summary>
        /// Gets an enumerator for the collection of rows
        /// </summary>
        /// <returns>The enumerator</returns>
        public IEnumerator<QueryRow> GetEnumerator()
        {
            return this.Rows.ToList().GetEnumerator();
        }

        /// <summary>
        /// Gets a generic enumerator for the collection of rows
        /// </summary>
        /// <returns>The generic enumerator</returns>
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }
}
