namespace Reportr.Components
{
    using Reportr.Data.Querying;

    /// <summary>
    /// Defines a contract for a single report component
    /// </summary>
    public interface IReportComponent
    {
        /// <summary>
        /// Gets the name of the component
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Gets the report component type
        /// </summary>
        ReportComponentType ComponentType { get; }
        
        /// <summary>
        /// Gets the components data source
        /// </summary>
        IQuery DataSource { get; }

        

        // TODO: data source bindings
        // TODO: relative size


        /// <summary>
        /// Generates the component output from the results of a query
        /// </summary>
        /// <param name="data">The data generated by the query</param>
        /// <returns>The output generated</returns>
        IReportComponentOutput GenerateOutput
        (
            QueryResults data
        );
    }
}
