namespace Reportr.Components
{
    using Reportr.Data.Querying;

    /// <summary>
    /// Defines a contract for a single report component
    /// </summary>
    public interface IReportComponent<TOutput> : IReportComponent
        where TOutput : IReportComponentOutput
    {
        /// <summary>
        /// Generates the component output from the results of a query
        /// </summary>
        /// <param name="data">The data generated by the query</param>
        /// <returns>The output generated</returns>
        new TOutput GenerateOutput
        (
            QueryResults data
        );
    }
}
