namespace Reportr.Data.Querying
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents the data for a single query grouping
    /// </summary>
    public sealed class QueryGrouping : IEnumerable<QueryRow>
    {
        /// <summary>
        /// Constructs the query grouping with the details
        /// </summary>
        /// <param name="groupingColumn">The grouping column</param>
        /// <param name="groupingValue">The grouping value</param>
        /// <param name="columns">The columns</param>
        /// <param name="rows">The rows</param>
        public QueryGrouping
            (
                QueryColumnInfo groupingColumn,
                object groupingValue,
                IEnumerable<QueryColumnInfo> columns,
                params QueryRow[] rows
            )
        {
            Validate.IsNotNull(groupingColumn);
            Validate.IsNotNull(columns);
            Validate.IsNotNull(rows);

            this.GroupingColumn = groupingColumn;
            this.GroupingValue = groupingValue;

            SetData(columns, rows);
        }
        
        /// <summary>
        /// Gets the grouping column
        /// </summary>
        public QueryColumnInfo GroupingColumn { get; private set; }

        /// <summary>
        /// Gets the grouping value
        /// </summary>
        public object GroupingValue { get; private set; }

        /// <summary>
        /// Gets an array of the rows in the result
        /// </summary>
        public QueryRow[] Rows { get; private set; }

        /// <summary>
        /// Sets the query grouping data
        /// </summary>
        /// <param name="columns">The queries columns</param>
        /// <param name="rows">The rows generated by the query</param>
        private void SetData
            (
                IEnumerable<QueryColumnInfo> columns,
                params QueryRow[] rows
            )
        {
            Validate.IsNotNull(columns);
            Validate.IsNotNull(rows);

            if (false == columns.Any())
            {
                throw new ArgumentException
                (
                    "At least one column is required to populate the query."
                );
            }

            foreach (var set in columns.ToList())
            {
                var name = set.Column.Name;

                var matchCount = columns.Count
                (
                    s => s.Column.Name.Trim().ToLower() == name.Trim().ToLower()
                );

                if (matchCount > 1)
                {
                    var message = "The column name '{0}' can only be used once.";

                    throw new ArgumentException
                    (
                        String.Format(message, name)
                    );
                }
            }

            ValidateRows
            (
                columns.ToArray(),
                rows
            );
            
            this.Rows = rows;
        }

        /// <summary>
        /// Validates a collection of rows against columns
        /// </summary>
        /// <param name="columns">The columns</param>
        /// <param name="rows">The rows to validate</param>
        private void ValidateRows
            (
                QueryColumnInfo[] columns,
                QueryRow[] rows
            )
        {
            var columnCount = columns.Length;

            foreach (var row in rows)
            {
                var cellCount = row.Cells.Length;

                if (cellCount != columnCount)
                {
                    var message = "{0} cells were expected, but {1} were found.";

                    throw new InvalidOperationException
                    (
                        String.Format
                        (
                            message,
                            columnCount,
                            cellCount
                        )
                    );
                }

                // Ensure the column names match those in the cells
                foreach (var info in columns)
                {
                    var matchFound = row.Cells.Any
                    (
                        c => c.Column.Name.ToLower() == info.Column.Name.ToLower()
                    );

                    if (false == matchFound)
                    {
                        var message = "No data was found for the column '{0}'.";

                        throw new InvalidOperationException
                        (
                            String.Format
                            (
                                message,
                                info.Column.Name
                            )
                        );
                    }
                }
            }
        }

        /// <summary>
        /// Gets the row at the index specified
        /// </summary>
        /// <param name="index">The row index (zero based)</param>
        /// <returns>The matching query row</returns>
        public QueryRow this[int index]
        {
            get
            {
                return this.Rows[index];
            }
        }

        /// <summary>
        /// Gets an enumerator for the collection of rows
        /// </summary>
        /// <returns>The enumerator</returns>
        public IEnumerator<QueryRow> GetEnumerator()
        {
            return this.Rows.ToList().GetEnumerator();
        }

        /// <summary>
        /// Gets a generic enumerator for the collection of rows
        /// </summary>
        /// <returns>The generic enumerator</returns>
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }
}
